// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace tp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250203134457_3")]
    partial class _3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Personnage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Armure")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<int>("Degats")
                        .HasColumnType("int");

                    b.Property<int>("NombrePersonnesTues")
                        .HasColumnType("int");

                    b.Property<int>("PointdsDeVie")
                        .HasColumnType("int");

                    b.Property<string>("Pseudo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Personnages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Armure = 150,
                            DateCreation = new DateTime(2025, 2, 3, 14, 44, 57, 556, DateTimeKind.Local).AddTicks(613),
                            Degats = 15,
                            NombrePersonnesTues = 0,
                            PointdsDeVie = 120,
                            Pseudo = "the boss"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
