// <auto-generated />
using Exercice4.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Exercice4.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Exercice4.Models.Marmoset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Poids")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Taille")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Marmosets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nom = "Ouistiti commun",
                            Poids = 0.35m,
                            Taille = 20m
                        },
                        new
                        {
                            Id = 2,
                            Nom = "Ouistiti pygmée",
                            Poids = 0.12m,
                            Taille = 15m
                        },
                        new
                        {
                            Id = 3,
                            Nom = "Ouistiti à pinceaux blancs",
                            Poids = 0.40m,
                            Taille = 23m
                        },
                        new
                        {
                            Id = 4,
                            Nom = "Ouistiti argenté",
                            Poids = 0.30m,
                            Taille = 22m
                        },
                        new
                        {
                            Id = 5,
                            Nom = "Ouistiti à toupet noir",
                            Poids = 0.38m,
                            Taille = 21m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
